### ISSUE TITLE
Incorrect port to expose in docker-compose.yml

### ISSUE THREAD

**Issue by trung674** [elastic/stack-docs#1511]
When I use a `docker-compose.yml` file from https://www.elastic.co/guide/en/elastic-stack-get-started/current/get-started-docker.html, I noticed that `es02` and `es03` elastic containers are exposing wrong ports. As the result, elsatic fails to create a cluster of 3 nodes.

It should be changed to:
```yaml
---
 es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
    ports:
      - 9201:9200 (change from 9201:9201)
    networks:
      - elastic

  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data03:/usr/share/elasticsearch/data
    ports:
      - 9202:9200 (change from 9202:9202)
    networks:
      - elastic
---
```

Provide the following information to help us identify and troubleshoot the issue.
- Page URL:  https://www.elastic.co/guide/en/elastic-stack-get-started/current/get-started-docker.html
-  Specifics (e.g., OS, Hardware, Browser, etc.): Docker Desktop on Windows (version 3.0.0), Docker Compose (version 1.27.4), Windows 10 Build 19042.685
